<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
defineProps({ ventas: Object, clientes: Array, filters: Object });
const form = useForm({});
function destroy(id) { if (confirm('Â¿Eliminar esta venta?')) form.delete(route('ventas.destroy', id)); }
</script>
<template>
    <AuthenticatedLayout><Head title="Ventas" /><div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        <div class="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3 mb-6"><h1 class="text-2xl font-semibold dark:text-white">Ventas</h1><Link :href="route('ventas.create')" class="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white self-start sm:self-auto">Nueva Venta</Link></div>
        <form class="mb-4 flex flex-col sm:flex-row flex-wrap gap-2"><select v-model="filters.cliente_id" class="w-full sm:w-auto theme-input text-sm" @change="$inertia.get(route('ventas.index'), { cliente_id: $event.target.value, estado: filters.estado }, { preserveState: true, replace: true })"><option value="">Todos los clientes</option><option v-for="c in clientes" :key="c.id" :value="c.id">{{ c.name }}</option></select><select v-model="filters.estado" class="w-full sm:w-auto theme-input text-sm" @change="$inertia.get(route('ventas.index'), { estado: $event.target.value, cliente_id: filters.cliente_id }, { preserveState: true, replace: true })"><option value="">Todos los estados</option><option value="PENDIENTE">Pendiente</option><option value="COMPLETADO">Completado</option><option value="ANULADO">Anulado</option></select></form>
        <div class="overflow-x-auto rounded-lg border dark:border-gray-700"><table class="min-w-full text-sm text-left text-gray-700 dark:text-gray-300"><thead class="bg-gray-50 dark:bg-gray-800"><tr><th class="px-4 py-3">ID</th><th class="px-4 py-3">Cliente</th><th class="px-4 py-3">Tipo</th><th class="px-4 py-3">Total</th><th class="px-4 py-3">Estado</th><th class="px-4 py-3">Fecha</th><th class="px-4 py-3 text-right">Acciones</th></tr></thead><tbody><tr v-for="v in ventas.data" :key="v.id" class="border-t dark:border-gray-700"><td class="px-4 py-3">{{ v.id }}</td><td class="px-4 py-3">{{ v.cliente?.name }}</td><td class="px-4 py-3">{{ v.tipo }}</td><td class="px-4 py-3">{{ v.total }}</td><td class="px-4 py-3">{{ v.estado }}</td><td class="px-4 py-3">{{ v.fecha }}</td><td class="px-4 py-3 text-right space-x-2"><Link :href="route('ventas.show', v.id)" class="text-blue-600 hover:underline text-xs">Ver</Link><button @click="destroy(v.id)" class="text-red-600 hover:underline text-xs">Eliminar</button></td></tr><tr v-if="!ventas.data.length"><td colspan="7" class="px-4 py-6 text-center text-gray-500 dark:text-gray-400">Sin ventas.</td></tr></tbody></table></div>
        <div class="mt-4 flex justify-center" v-if="ventas.links"><div class="flex flex-wrap gap-1 text-sm"><Link v-for="link in ventas.links" :key="link.label" :href="link.url || '#'" v-html="link.label" class="px-3 py-1 rounded border dark:border-gray-600 dark:text-gray-300" :class="{'bg-indigo-600 text-white': link.active, 'opacity-50 pointer-events-none': !link.url}" /></div></div>
    </div></AuthenticatedLayout>
</template>

